### ISSUE TITLE
Sweep: Add a new python file named test.py that prints hello world

### ISSUE THREAD

**Issue by mehulgupta2016154** [mehulgupta2016154/Traffic_Turbo#3]
<details open>
<summary>Checklist</summary>

- [X] ``.github/workflows/test.yml`` ✅ Commit <a href='https://github.com/mehulgupta2016154/Traffic_Turbo/commit/0536274153dca6ac5b8d0b7d0285ec7cbdafa2b1'><code>0536274</code></a>
- [X] `.github/workflows/test.yml` ✅ Sandbox ran successfully
- [X] `.github/workflows/test.yml` ✅ Sandbox ran successfully
- [X] `.github/workflows/test.yml` ❌ Sandbox failed so I made additional changes
- [X] ``test.py`` ✅ Commit <a href='https://github.com/mehulgupta2016154/Traffic_Turbo/commit/1ab282c826f1e5ed5bc4ce337e477e7820166e2f'><code>1ab282c</code></a>
- [X] `test.py` ✅ Sandbox ran successfully

![Flowchart](http://24.199.78.105:8082/public/addefa9269d1841e02c962a894de45d88943cb3ec370cc8ef0a48d021d1e86de_3_flowchart.svg)
</details>

**Comment by mehulgupta2016154** [comment]
Unable to Complete PR. Why?

**Comment by wwzeng1** [comment]
Sweep: retry
